modLoader="javafml"
loaderVersion="[61,)"
license="MIT License"
[[mods]]
modId="beefix"
version="${file.jarVersion}"
displayName="Bee Fix"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bee-fix"
displayTest="IGNORE_SERVER_VERSION"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Bee Fix Mod fixes several Minecraft bugs related to Bees.'''
[[dependencies.beefix]]
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beefix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,1.22)"
    ordering="NONE"
    side="BOTH"
